spring.application.name=apigateway
server.port=8080


spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=${ORDER_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/orders/**

app.jwt.secret=${JWT_SECRET}
app.jwt.whitelist[0]=/auth/login
app.jwt.whitelist[1]=/auth/register
app.jwt.whitelist[2]=/auth/refresh

management.endpoints.web.exposure.include=health,info